# # General configuration
#
# Port to listen on (do not use in Docker installations)
# port = "$PORT"
#
# Key used to sign tokens used to verify requests.
# secret_key = ""
#
# Sentry DSN key used to report errors
# sentry_dsn = ""

# # Store definition
#
# Each store is defined in form
#
#       [stores.<path>]
#       type = "Local" # case sensitive
#
# Each store can also be provided with additional options in form
#
#       [stores.<path>.options]
#       bucket = "upload"
#
# There is also possibility to define store and cache separately via
#
#       [stores.<path>.store]
#       type = "S3"
#               [stores.<path>.store.config]
#               bucket = "uploads"
#       [stores.<path>.cache]
#       type = "Local"
#               [stores.<path>.cache.config]
#               dir = "/tmp/cache"

# # Environment variable expansion
#
# Each string value can be expanded using environment variable.  Given string
# needs to be in form `$env_name`, ex.:
#
#       secret_key = "$SECRET_KEY"
#
# There is no way to cast given variable to different type

# # Store types

# ## S3
#
# Store that uses S3-compatible service as a remote store.
#
# Available options:
# `bucket` (required) - bucket name for given storage
# `region` (required) - AWS storage region
# `host` - host to S3-compatible service (without scheme or port), ex.:
#          'localhost'.  Defaults to AWS
# `scheme` - scheme to use, MUST end with '://'.  Defaults to 'https://'
# `port`  - communication port.  Defaults to whatever is default port for
#           `scheme`
# `virtual_host` - whether use virtual hosts for AWS or not, boolean.

# [stores.upload]
# type = "S3"
#     [stores.upload.options]
#     bucket = "upload"
#     host = "$S3_HOST"
#     scheme = "$S3_SCHEME"
#     port = "$S3_PORT"
#     region = "eu-west-1"

# ## Local
#
# Store that uses local directory.
#
# Available options:
# `dir` (required) - directory where images are/will be stored

# [stores.local]
# type = "Local"
#     [stores.local.options]
#     dir = "/var/imager"

# ## Blackhole
#
# Store that discards all writes and always fail on read.
#
# Can be useful when using CDN and we do not want to store images at all and
# rely on extrnal caching system.

# [stores.dump]
# type = "Blackhole"
